spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: false
    show-sql: true
  h2.console.enabled: true # the JDBC URL is jdbc:h2:mem:testdb

  # use this when using multiple spring main classes in same project
#  main.allow-bean-definition-overriding: true