#server:
#  port: 8081

#  servlet:
#    context-path: /resource-server-jwt
#
#spring:
#  security:
#    oauth:
#      resourceserver:
#        jtw:
#          # defines path to authorization server, so that resource server can discover it
#          issuer-uri: http://localhost:8082/auth/realms/sda